spring:
  application:
    name: ip-context-service
  docker:
    compose:
      lifecycle-management: start-only
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:{MYSQL_PORT:3306}/${IP_CONTEXT_DB_NAME:IP_CONTEXT}
    username: ${MYSQL_DB_NAME:dummy}
    password: ${MYSQL_DB_PASSWORD:password}
management:
  endpoints:
    web:
      exposure:
        include: "*"

client:
  timeout: 10000
  read-timeout: 10000

ip-api:
  scheme: https
  host: api.ipapi.com
  port: -1
  path: api/{ipAddress}
  access-key: 272e6b7557030b76e5d04e2325d8ea86

geography-api:
  scheme: https
  host: api.apilayer.com
  port: -1
  path: geo/country/code/{countryCode}
  apikey: yZbci6tDYm2Huog33iR7icBM0Z5zXAWF

fixer-api:
  scheme: https
  host: api.apilayer.com
  port: -1
  path: fixer/latest
  apikey: yZbci6tDYm2Huog33iR7icBM0Z5zXAWF
